#####################################################################################
###################################### Variables ####################################
substitutions:
  board_name: ESP Cat Litter Tonepie
  node_name: cat litter tonepie

#####################################################################################
################################# Basic configuration ###############################
esphome:
  name: cat-litter-tonepie
  friendly_name: cat-litter-tonepie
  comment: ESP Cat Litter Tonepie

#####################################################################################
####################################### Platform ####################################
esp8266:
  board: esp12e
  framework:
    version: recommended
  restore_from_flash: true #We save the preset settings. After a reboot, the settings are not reset

#Resetting data to the flash drive to reduce the wear of the flash drive
preferences:
  flash_write_interval: 1min

#####################################################################################
################################ WiFi and access point ##############################
#Wi-Fi credentials for connecting the board to the home network
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: off
  reboot_timeout: 5min

#If there is no connection with WiFi, then the access point will rise
  ap:
    ssid: ESP Cat Litter Tonepie
    password: !secret ap_esp_password
    ap_timeout: 1 min
    manual_ip:
      static_ip: 192.168.4.1
      gateway: 192.168.4.1
      subnet: 255.255.255.0

#The mdns component forces the node to announce itself on the local network using the DNS Multicast Protocol (mDNS), by default for mDNS disabled: false
mdns:
  disabled: false

#The captive portal component in ESPHome is a backup mechanism in case the connection to the configured Wi-Fi fails
captive_portal:

#Web server
web_server:
  port: 80

#Logging
logger:
  baud_rate: 0

#Enable Home Assistant API
api:

#Over-the-Air Update (OTA)
ota:
  password: "esphome"

#####################################################################################
######################################### UART ######################################
uart:
  tx_pin: GPIO1
  rx_pin: GPIO3
  baud_rate: 9600
  stop_bits: 1
  data_bits: 8
  parity: none
  debug:
    direction: BOTH
    dummy_receiver: false

#Enable the Tuya MCU component
tuya:


#####################################################################################
##################################### Switch ########################################
switch:
  - platform: "tuya"
    name: "Auto Cleaning"
    icon: mdi:auto-mode
    id: idAutoCleaning
    switch_datapoint: 105

  - platform: "tuya"
    name: "Manual Cleaning"
    icon: mdi:broom
    id: idManualCleaning
    switch_datapoint: 101

  - platform: "tuya"
    name: "Remove Filler"
    icon: mdi:trash-can-outline
    id: idRemoveFiller
    switch_datapoint: 102

  - platform: "tuya"
    name: "Infrared Sensor"
    icon: mdi:eye-outline
    id: idInfraredSensor
    switch_datapoint: 111

  - platform: "tuya"
    name: "Protection From Children"
    icon: mdi:lock-check-outline
    id: idProtectionFromChildren
    switch_datapoint: 114

  - platform: "tuya"
    name: "Ionizer"
    icon: mdi:creation
    id: idIonizer
    switch_datapoint: 120

  - platform: "tuya"
    name: "Auto Odor Purification Switch"
    icon: mdi:creation-outline
    id: idAutoOdorPurificationSwitch
    switch_datapoint: 126

#####################################################################################
################################## Sensor ###########################################
sensor:
  - platform: wifi_signal
    name: "RSSI WiFi"
    icon: mdi:wifi
    update_interval: 60s

    name: "Cat Weight"
    icon: mdi:scale
    id: idCatWeight
    unit_of_measurement: g
    sensor_datapoint: 6

  - platform: "tuya"
    name: "Visit Time"
    icon: mdi:clock-outline
    id: idVisitTime
    unit_of_measurement: sec
    sensor_datapoint: 8


#####################################################################################
###################################### Text sensor ##################################
text_sensor:
  - platform: wifi_info
    ip_address:
      name: IP
      icon: mdi:ip-network

  - platform: version
    name: "ESPHome Version"
    hide_timestamp: true

  - platform: template
    name: "Uptime"
    icon: mdi:clock-start
    id: uptime_esp
    entity_category: diagnostic

  - platform: template
    name: "Time"
    icon: mdi:clock-digital
    id: idTime
    update_interval: 10s
    lambda: |-
      auto time_text = id(homeassistant_time).now().strftime("%H:%M:%S / %d-%m-%Y");
      return { time_text };


#####################################################################################
################################### Binary sensor ###################################
binary_sensor:
  - platform: "tuya"
    name: "Trash Can"
    sensor_datapoint: 119

  - platform: "tuya"
    name: "Cleaning"
    sensor_datapoint: 121

  - platform: "tuya"
    name: "Pet Inside"
    icon: mdi:scale-unbalanced
    id: idPetInside
    sensor_datapoint: 104


#####################################################################################
###################################### Number #######################################
number:
  - platform: "tuya"
    name: "Launch delay"
    icon: mdi:timer-play-outline
    id: idLaunchDelay
    number_datapoint: 117
    min_value: 0
    max_value: 60
    step: 1
    mode: box #slider/box

  - platform: "tuya"
    name: "Interval Between Cleaning"
    icon: mdi:clock-time-eight-outline
    id: idIntervalBetweenCleaning
    number_datapoint: 118
    min_value: 0
    max_value: 120
    step: 1
    mode: box #slider/box

  - platform: "tuya"
    name: "Calibration Of The Waste Tank"
    icon: mdi:delete-variant
    id: idCalibrationOfTheWasteTank
    number_datapoint: 124
    min_value: 0
    max_value: 15
    step: 1
    mode: box #slider/box

  - platform: "tuya"
    name: "Calibration Of Filler"
    icon: mdi:basket-unfill
    id: idCalibrationOfFiller
    number_datapoint: 125
    min_value: 0
    max_value: 6
    step: 1
    mode: box #slider/box

  - platform: "tuya"
    name: "Detection Sensitivity"
    icon: mdi:signal-variant
    id: idDetectionSensitivity
    number_datapoint: 127
    min_value: 0
    max_value: 1500
    step: 1
    mode: box #slider/box

  - platform: "tuya"
    name: "Cat Weight"
    icon: mdi:scale
    id: idCatWeight
    number_datapoint: 6
    min_value: 600
    max_value: 10000
    step: 1
    mode: box #slider/box
    unit_of_measurement: g

#####################################################################################
####################################### Button ######################################
button:
  - platform: restart
    name: "Restart"
    icon: mdi:restart

#####################################################################################
######################################## Time #######################################
time:
  - platform: homeassistant
    id: homeassistant_time